services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=article'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_USER=spring'
    ports:
      - '3306:3306'
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d